import React, { FC } from 'react';

type LeaderBoardProps = {
    closeHandler: () => void
};

const LeaderBoard: FC<LeaderBoardProps> = ({closeHandler}) => {
    return <>
    <button title="Lukk ledertavle" id="CloseLeaderboard" onClick={() => closeHandler()}>
      {/*X-icon svg*/}
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18"><path fill="#fff" d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"/></svg>
      </button>
    <h2>SNILLE BARN</h2>
    <table>
        <thead>
        <tr>
            <th>LUKER LØST</th>
            <th>BRUKERNAVN</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        <tr>
            <td>24</td>
            <td>Sverre</td>
        </tr>
        
        
        </tbody>
    </table>
    </>;
}

export default LeaderBoard;